image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - test

build_node:
  stage: build
  script:
   - npm install
  tags:
    - docker

test_node:
  stage: test
  script:
    - npm install
    - npm test
  tags:
    - docker