const DATABASE_SERVICE = {
  NEDB: "NEDB"
};

const MAIL_SERVICE = {
  GMAIL: "GMAIL"
};

const PASSWORD_SERVICE = {
  BCRYPT: "BCRYPT"
};

const TOKEN_SERVICE = {
  JWT: "JWT"
};

// Enum containing actions validated by a json web token
const JWT_ACTIONS = {
  LOGIN: "LOGIN",
  VERIFY_ACCOUNT: "VERIFY_ACCOUNT",
  ALLOW_CONNECTION: "ALLOW_CONNECTION",
  RESET_PASSWORD: "RESET_PASSWORD"
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  DUPLICATE: 409,
  INTERNAL_ERROR: 500,
  NOT_IMPLEMENTED: 501
};

const ERROR_CODES = {
  OK: 0,
  SERVER_FAILURE: -1,
  UNIQUE_MAIL: -2,
  WRONG_CREDENTIALS: -3,
  TOO_MANY_ATTEMPTS: -4,
  MAIL_ERROR: -5,
  WRONG_TOKEN: -6
};

module.exports = {
  DATABASE_SERVICE: DATABASE_SERVICE,
  MAIL_SERVICE: MAIL_SERVICE,
  PASSWORD_SERVICE: PASSWORD_SERVICE,
  TOKEN_SERVICE: TOKEN_SERVICE,
  JWT_ACTIONS: JWT_ACTIONS,
  HTTP_STATUS: HTTP_STATUS,
  ERROR_CODES: ERROR_CODES
};
